blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/muhammad-fiaz/acceleratesearch#readme
    about: Check the documentation for common questions
  - name: Discussions
    url: https://github.com/muhammad-fiaz/acceleratesearch/discussions
    about: Ask questions and discuss ideas
